workflow improvements
bump workflow
- add publish

publish workflow
- add cancel in progress
- disable for bot actions
- improve check for already published version

all workflows
- replace cd with working directory
- set npm user config to /dev/null
- list npm config
- refactor

diff --git a/.github/workflows/publish-shared.yml b/.github/workflows/publish-shared.yml
--- a/.github/workflows/publish-shared.yml
+++ b/.github/workflows/publish-shared.yml
@@ -9,31 +9,46 @@ on:
             - 'shared/tsconfig.json'
             - 'shared/src/**'
 
+concurrency:
+    group: deploy-${{ github.ref_name }}
+    cancel-in-progress: true
+
 permissions:
     contents: read
     packages: write
 
 jobs:
     publish:
-        if: ${{ github.actor != 'dependabot[bot]' }}
+        if: ${{ endsWith(github.actor, '[bot]') == false }}
         runs-on: 'self-hosted'
         steps:
             - name: checkout
               uses: actions/checkout@v4
 
+            - name: setup node
+              uses: actions/setup-node@v4
+              with:
+                  node-version: 'lts/*'
+                  check-latest: true
+                  cache: 'npm'
+                  cache-dependency-path: shared/package-lock.json
+
             - name: create .npmrc
+              working-directory: shared
               run: |
-                  cd shared/
                   echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_NPM_TOKEN }}" >> .npmrc
                   echo "@aditya-arcot:registry=https://npm.pkg.github.com/" >> .npmrc
 
             - name: check if version already published
               id: check-version
+              working-directory: shared
               run: |
-                  cd shared/
+                  npm --userconfig=/dev/null config ls
+
                   VERSION=$(jq -r .version package.json)
                   PACKAGE_NAME="@aditya-arcot/wealthwatch-shared"
-                  if PUBLISHED=$(npm view "$PACKAGE_NAME" version --registry=https://npm.pkg.github.com/ 2> /dev/null); then
+
+                  if PUBLISHED=$(npm --userconfig=/dev/null view "$PACKAGE_NAME" version --registry=https://npm.pkg.github.com/ 2>&1); then
                     echo "Latest published version is $PUBLISHED"
                     if [ "$VERSION" = "$PUBLISHED" ]; then
                       echo "Package version $VERSION already published"
@@ -43,31 +58,28 @@ jobs:
                       echo "skip_publish=false" >> $GITHUB_OUTPUT
                     fi
                   else
-                    echo "Could not get published package version"
-                    exit 1
+                    if echo "$PUBLISHED" | grep -q "E404"; then
+                        echo "Package has never been published"
+                        echo "skip_publish=false" >> $GITHUB_OUTPUT
+                    else
+                        echo "Could not get published package version"
+                        echo "npm error: $PUBLISHED"
+                        exit 1
+                    fi
                   fi
-
-            - name: setup node
-              if: steps.check-version.outputs.skip_publish == 'false'
-              uses: actions/setup-node@v4
-              with:
-                  node-version: 'lts/*'
-                  check-latest: true
-                  cache: 'npm'
-                  cache-dependency-path: shared/package-lock.json
 
             - name: install, build
               if: steps.check-version.outputs.skip_publish == 'false'
+              working-directory: shared
               run: |
-                  cd shared/
-                  npm ci
-                  npm run build
+                  npm --userconfig=/dev/null config ls
+                  npm --userconfig=/dev/null ci
+                  npm --userconfig=/dev/null run build
 
             - name: publish
               if: steps.check-version.outputs.skip_publish == 'false'
-              env:
-                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+              working-directory: shared
               run: |
-                  cd shared/
-                  npm whoami --registry=https://npm.pkg.github.com/
-                  npm publish --access public
+                  npm --userconfig=/dev/null config ls
+                  npm --userconfig=/dev/null whoami --registry=https://npm.pkg.github.com/
+                  npm --userconfig=/dev/null publish --access public
